config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :courses
  resources :departments
  resources :institutes
  devise_for :users

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:index, :show, :create, :destroy]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/models/institute.rb
class Institute < ActiveRecord::Base
  has_many :departments, dependent: :destroy

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100#", :small => "150x150>" },
  :default_url => "/images/:style/imgdirectory.png"
  #validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  # Validations
  validates_attachment :picture,
  :size => { :in => 0..10.megabytes },
  :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  before_action :set_institute, only: [:show, :edit, :update, :destroy]

  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
   # @institute = Institute.new
    #@institutes = Institute.all
    #@institute = institute.find(params[:id])
    # @departments = Department.all
    #@department = department.find(params[:id])
  end

  # GET /institutes/new
  def new
    @institute = Institute.new
  end

  # GET /institutes/1/edit
  def edit
  end

  # POST /institutes
  # POST /institutes.json
  def create
    @institute = Institute.new(institute_params)

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Instituto criado com sucesso.' }
        format.json { render :show, status: :created, location: @institute }
      else
        format.html { render :new }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutes/1
  # PATCH/PUT /institutes/1.json
  def update
    respond_to do |format|
      if @institute.update(institute_params)
        format.html { redirect_to @institute, notice: 'Instituto editado com sucesso.' }
        format.json { render :show, status: :ok, location: @institute }
      else
        format.html { render :edit }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    @institute.destroy
    respond_to do |format|
      format.html { redirect_to institutes_url, notice: 'Instituto destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institute
      @institute = Institute.find(params[:id])
      @departments = @institute.departments.all
      @department = @institute.departments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institute_params
      params.require(:institute).permit(:name, :description, :picture)
    end
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_for @institute, :html => {:multipart => true} do |f| %>
  <% if @institute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institute.errors.count, "error") %> prohibited this institute from being saved:</h2>

      <ul>
      <% @institute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description, "Descrição" %><br>
    <%= f.text_area :description, autofocus: true, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :picture, "Imágem" %><br>
    <%= f.file_field :picture, autofocus: true, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit "Criar Instituto", class:'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/institutes/_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
  Editar
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <%= link_to 'Show', @institute, class:'btn btn-default' %> |
        <%= link_to 'Back', institutes_path, class:'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/institutes/edit.html.erb
<% provide(:title, "Editar #{@institute.name}") %>
<div class="panel panel-info">
	<div class="panel-heading text-center">	
		<h1>Editar Instituto</h1>
	</div>
	<div class="panel-body">

		<%= render 'form' %>
	</div>
</div>

<div class="well well-sm text-center">
	<%= link_to 'Ver', @institute, class:'btn btn-primary btn-sm' %> |
	<%= link_to 'Voltar', institutes_path, class:'btn btn-primary btn-sm' %>
</div>

app/views/institutes/index.html.erb
<% provide(:title, "Institutos") %>
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h1>Lista de Institutos</h1><h5><%= @institutes.count %> Instituto(s)</h5>
  </div>
  <div class="panel-body">
    <%= link_to 'Novo Instituto', new_institute_path, class:'btn btn-primary btn-lg btn-block' %>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Imágem</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @institutes.each do |institute| %>
            <tr>
              <td><%= image_tag institute.picture.url(:thumb) %></td>
              <td><%= institute.description %></td>
              <td><%= institute.name %></td>
              <td><%= link_to 'Ver', institute, class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Editar', edit_institute_path(institute), class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Destruir', institute, method: :delete, data: { confirm: 'Você tem certeza de que deseja destruir este instituto permanentemente?' }, class:'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'Novo Instituto', new_institute_path, class:'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
</div>

app/views/institutes/new.html.erb
<% provide(:title, "Criar Instituto") %>
<div class="panel panel-info">
	<div class="panel-heading text-center">
		<h1>Novo Instituto</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>
<div class="well well-sm text-center">
	<%= link_to 'Voltar', institutes_path, class:'btn btn-primary' %>
</div>

app/views/institutes/show.html.erb
<% provide(:title, "#{@institute.name}") %>
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading text-center">
    <h4>
		  <strong><%= @institute.name %></strong>
		</h4>
	</div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-hover">
    		<tr>
    			<td rowspan="3">
    				<%= image_tag @institute.picture.url(:thumb) %>
    			</td>
    			<td>
		 				<strong>Descrição:</strong>
		 		  	<%= @institute.description %>
		 		  </td>
		 		</tr>
		 		<tr>
		 			<td>Criado em: <%= @institute.created_at.to_s(:created) %></td>
		 		</tr>
        <tr>
          <td>Atualizado em: <%= @institute.updated_at.to_s(:updated) %></td>
        </tr>
      </table>
    </div>
		<div class="well well-sm text-center">
			<%= link_to 'Editar', edit_institute_path(@institute), class:'btn btn-primary btn-sm' %> |
			<%= link_to 'Voltar', institutes_path, class:'btn btn-primary btn-sm' %>
		</div>
	</div>
</div>

<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h3>Lista de Departamentos</h3><h5><%= @departments.count %> Departamento(s)</h5>
  </div>
  <div class="panel-body">
    
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Imágem</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @departments.each do |department| %>
            <tr>
              <td><%= image_tag department.picture.url(:thumb) %></td>
              <td><%= department.name %></td>
              <td><%= department.description %></td>
              <td><%= link_to 'Ver', department, class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Editar', edit_department_path(department), class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Destruir', department, method: :delete, data: { confirm: 'Você tem certeza de que deseja destruir este departamento permanentemente?' }, class:'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      
    </div>
  </div>
</div>
<%= render 'departments/form' %>