config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :courses
  resources :departments
  resources :institutes
  devise_for :users

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:index, :show, :create, :destroy]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :conversations, :foreign_key => :sender_id

  after_create :create_default_conversation

  # FRIENDSHIP
  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :posts, dependent: :destroy


  def request_friendship(user_2)
    self.friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
    self.inverse_friendships.where(state: "pending")
  end

  def pending_friend_requests_to
    self.friendships.where(state: "pending")
  end

  def active_friends
    self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end

  def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id])
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end

  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id]).first
  end

  # THING
  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end

  private

  # for demo purposes

  def create_default_conversation
    Conversation.create(sender_id: 1, recipient_id: self.id) unless self.id == 1
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:create, :edit, :update, :destroy]
  # before_action :authenticate_user!
  before_filter :authenticate_user!
  before_action :get_counts, only: [:index]

  def index
    # @users = User.all we will replace this old code - you can delete this line

    # PAGINATE
    @users = User.page(params[:page]).per(30)
    # CHATTY
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user).order("created_at DESC")
    # @sent_invites = current_user.sent_invites YOU CAN DELETE THIS LINE
    # @received_invites = current_user.received_invites YOU CAN DELETE THIS LINE

    # @sent_invites = current_user.sent_invites.page(params[:page])
    # @received_invites = current_user.received_invites.page(params[:page])

    # FRIENDSHIP
    case params[:people] when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
      @users = current_user.pending_friend_requests_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end 
  end

  def show
    @user = User.find(params[:id])
  end

    def new
    @user = User.new
  end

# GET /users/1/edit
  def edit
  end
 
  # POST /users
  def create
    @user = User.new(user_params)
    has_attached_file :picture
    if @user.save
      redirect_to users_url
    else
      render action: 'new'
    end
  end
 
  # PATCH/PUT /users/1
  def update
    if user_params[:password].blank?
      @user.update_without_password(user_params_without_password)
    else
      @user.update(user_params)
    end
 
    if @user.valid?
      if @user == current_user
        sign_in(@user, bypass: true)
      end
 
      redirect_to users_url
    else
      render action: 'edit'
    end
  end
 
  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuário excluído.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_params_without_password
    user_params.delete(:password)
    user_params.delete(:password_confirmation)
    user_params
  end

  # FRIENDSHIP
  def get_counts
    @friend_count = current_user.active_friends.size
    @pending_count = current_user.pending_friend_requests_to.map(&:friend).size
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# CHATTY
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end

  # FRIENDSHIP
  def action_buttons(user)
  	case current_user.friendship_status(user) when "friends"
			link_to "Cancel Friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "pending"
			link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "requested"
			link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put
		when "not_friends"
			link_to "Add as Friend", friendships_path(user_id: user.id), method: :post
		end
	end
end

app/views/users/index.html.erb
<% provide(:title, "Usuários") %>
<div class="jumbotron text-center">
<h2>People</h2>
<div class="btn-group" role="group" aria-label="Default Button Groups">
<%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
<%= link_to "Friends (#{@friend_count})", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
<%= link_to "Requests (#{request_count})", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
<%= link_to "Pending (#{@pending_count})", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
</div>
</div>

<div class="container">
  <div>
  	
  	<table class="responsive">
  		<tbody>
		    <% @users.each do |user| %>
		    	<tr>
		    		<td>
					    <div class="panel panel-default">
					      <%= link_to user_path(user) do %>
					      <div class="panel-body">
					        <%= image_tag(user.avatar.url(:medium)) %>
					        <p><%= user.full_name %></p>
                  <% if current_user %>
                    <p><%= action_buttons(user)%></p>
                  <% end %>
					      </div>
					      <% end %>
					    </div>
					  </td>
					  <td><%= link_to 'Editar perfil', edit_user_registration_path %></td>
        		<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				  </tr>
		    <% end %>
	  	</tbody>
	  </table>
    
  </div>
</div>


<div class="row">
  <!-- Not implemented on tutorial -->
  <div class="col-md-4">
    <div style="height: 300px; overflow-y: auto;">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Registered Users</div>

        <!-- Table -->
        <table class="table">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each_with_index do |user, index| %>
              <tr>
                <td><%= index +=1 %></td>
                <td><%= user.name %></td>
                <td>
                  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_user.id, "data-rip" => user.id %>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    </div>
    <hr>
    <h3>Your Conversations</h3>

    <div style="height: 400px; overflow-y: auto;">
      <% if @conversations.any? %>
          <ul class="media-list">
            <% @conversations.each do |conversation| %>
                <li class="media">
                  <%= image_tag("http://placehold.it/50x50", class: "media-object pull-left") %>
                  <div class="media-body">
                    <%= link_to "", conversation_path(conversation), class: "conversation", "data-cid" => conversation.id %>
                        <h4 class="media-heading"><%= conversation_interlocutor(conversation).name %></h4>
                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                </li>

            <% end %>
          </ul>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>
    </div>
  </div>

  <div class="col-md-4">

  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Perfil") %>
<h1>SOA UFBA</h1>

<div class="row profile">
    <div class="col-sm-4 col-md-1">
      <%= image_tag(@user.avatar.url(:medium), class: 'avatar') %>
      <h3><%= @user.full_name %></h3>
      <ul>
        <%= content_tag(:li, ("Nome: " + @user.name)) unless @user.name.blank? %>
      </ul>
    </div>
    <div class="feed">
        <h3>Conectando você com a Ufba</h3>
        <p>Aqui ficará seu feed de notícias</p>
    </div>
</div>