config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :courses
  resources :departments
  resources :institutes
  devise_for :users

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:index, :show, :create, :destroy]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/models/department.rb
class Department < ActiveRecord::Base
	has_many :courses, dependent: :destroy
	belongs_to :institute

  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100#" }, 
  :default_url => "/images/:style/imgdirectory.png"
  #validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  # Validations
  validates_attachment :picture,
  :size => { :in => 0..10.megabytes },
  :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
   # @department = Department.new
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    # @departments = Department.all
    #CHANGEEEEEEEE
    #@department = Department.find(params[:id])
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
    #CHANGEEEEEEEE
    #@department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Departamento criado com sucesso.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Departamento editado com sucesso.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Departamento destruído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
      @courses = @department.courses.all
      @course = @department.courses.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :description, :picture, :institute_id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department, :html => {:multipart => true} do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description, "Descrição" %><br>
    <%= f.text_area :description, autofocus: true, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :picture, "Imágem" %><br>
    <%= f.file_field :picture, autofocus: true, class: "form-control" %>
  </div>
  <!-- CHAVE -->
  <%= f.hidden_field :institute_id %>
  <div class="actions form-group">
    <%= f.submit "Criar Departamento", class:'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<% provide(:title, "Editar #{@department.name}") %>
<div class="panel panel-info">
	<div class="panel-heading text-center">	
		<h1>Editar Departmento</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
</div>

<div class="well well-sm text-center">
	<%= link_to 'Ver', @department, class:'btn btn-primary btn-sm' %> |
	<%= link_to 'Voltar', departments_path, class:'btn btn-primary btn-sm' %>
</div>

app/views/departments/index.html.erb
<% provide(:title, "Departamentos") %>
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h1>Lista de Departamentos</h1><h5><%= @departments.count %> Departamento(s)</h5>
  </div>
  <div class="panel-body">
    <%= link_to 'Novo Departamento', new_department_path, class:'btn btn-primary btn-lg btn-block' %>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Imágem</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @departments.each do |department| %>
            <tr>
              <td><%= image_tag department.picture.url(:thumb) %></td>
              <td><%= department.name %></td>
              <td><%= department.description %></td>
              <td><%= link_to 'Ver', department, class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Editar', edit_department_path(department), class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Destruir', department, method: :delete, data: { confirm: 'Você tem certeza de que deseja destruir este departamento permanentemente?' }, class:'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'Novo Departamento', new_department_path, class:'btn btn-primary btn-lg btn-block' %>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<% provide(:title, "Criar Departamento") %>
<div class="panel panel-info">
	<div class="panel-heading text-center">
		<h1>Novo Departmento</h1>
	</div>
	<div class="panel-body">

		<%= render 'form' %>
	</div>
</div>
<div class="well well-sm text-center">
	<%= link_to 'Voltar', departments_path, class:'btn btn-primary' %>
</div>

app/views/departments/show.html.erb
<% provide(:title, "#{@department.name}") %>
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
  <div class="panel-heading text-center">
		<h1>
		  <strong><%= @department.name %></strong>
		</h1>
	</div>
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-hover">
    		<tr>
    			<td rowspan="3">
    				<%= image_tag @department.picture.url(:thumb) %>
    			</td>
    			<td>
		 				<strong>Descrição:</strong>
		 		  	<%= @department.description %>
		 		  </td>
		 		</tr>
		 		<tr>
		 			<td>Criado em: <%= @department.created_at.to_s(:created) %></td>
		 		</tr>
        <tr>
          <td>Atualizado em: <%= @department.updated_at.to_s(:updated) %></td>
        </tr>
      </table>
    </div>
		<div class="well well-sm text-center">
			<%= link_to 'Editar', edit_department_path(@department), class:'btn btn-primary' %> |
			<%= link_to 'Voltar', departments_path, class:'btn btn-primary' %>
		</div>
	</div>
</div>
<div class="panel panel-default">
  <div class="panel-heading text-center">
    <h1>Lista de Cursos</h1><h5><%= @courses.count %> Curso(s)</h5>
  </div>
  <div class="panel-body">
    <%= link_to 'Novo Curso', new_course_path, class:'btn btn-primary btn-lg btn-block' %>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Imágem</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td><%= image_tag course.picture.url(:thumb) %></td>
              <td><%= course.name %></td>
              <td><%= course.description %></td>
              <td><%= link_to 'Ver', course, class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Editar', edit_course_path(course), class:'btn btn-primary btn-xs' %></td>
              <td><%= link_to 'Destruir', course, method: :delete, data: { confirm: 'Você tem certeza de que deseja destruir este curso permanentemente?' }, class:'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    </div>
  </div>
</div>

<%= render 'courses/form' %>