config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :courses
  resources :departments
  resources :institutes
  devise_for :users

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users, only: [:index, :show, :create, :destroy]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>


<script>
    $('.alert').fadeOut(4000);
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-default navbar-static-bottom">
      <small> The Software Engennie I - Max, Victor, Arley.
      </small>
      <nav>
        <ul>
          <li><%= link_to "Sobre",   about_path %></li>
          <li><%= link_to "Contato", contact_path %></li>
          <li><%= link_to "News", news_path %></li>
        </ul>
      </nav>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">SOA</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-menubuilder">
      <ul class="nav navbar-nav navbar-left">
          <li class="active"><%= link_to "Home", root_path %>
          </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              <ul>
                <%= link_to user_path(current_user) do %>
                  <li class="round-image-50">
                    <%= image_tag(current_user.avatar.url(:thumb)) %>
                  </li>
                <% end %>
              </ul>
            <li><strong><%= current_user.email %></strong>.</li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true">Conta</span><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %>
                </li>
                <li><%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
                <li class="divider"></li>
                <li><%= link_to "Ajuda", help_path, :class => 'navbar-link' %>
                </li>
              </ul>
            </li>
          <% else %>
            <%= link_to "Ajuda",   help_path, :class => 'navbar-link' %> | 
            <%= link_to "Cadastre se", new_user_registration_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>

    <title><%= yield(:title) %> | SOA - Sistema de Orientação Acadêmica da Ufba!</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
    	<% if notice %>
   		 	<p class="alert alert-success" role="alert"><%= notice %></p>
  		<% end %>
  		<% if alert %>
    		<p class="alert alert-danger" role="alert"><%= alert %></p>
  		<% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>
  </body>
</html>